dist: xenial

language: c

compiler:
  - gcc

sudo: required

services:
  - docker

install:
  - sudo apt-get -qq update
  - sudo apt-get --yes --assume-yes install
      autoconf
      automake
      bash
      bc
      bison
      bsdiff
      build-essential
      chrpath
      cmake
      cpio
      diffstat
      flex
      gawk
      gcovr
      git
      gperf
      iputils-ping
      libbz2-dev
      libcurl4-gnutls-dev
      libncurses5-dev
      libncursesw5-dev
      libsdl-dev
      libssl-dev
      libtool
      libxml2-utils
      ninja-build
      python
      python-git
      python-jinja2
      python-pkg-resources
      python3
      texinfo
      unzip
      wget
      zlib1g-dev
  - sudo apt-get --yes --assume-yes install openjdk-8-jdk phablet-tools
  - git config --global color.ui false
  - git config --global user.name "Travis"
  - git config --global user.email "legato@travis-ci.org"

script:
  - cd ..
  - mkdir workspace
  - cd workspace
  - export MANIFEST_REPO=${MANIFEST_REPO:-https://github.com/legatoproject/manifest}
  - if [ -n "$TRAVIS_TAG" ]; then
       repo init -q -u $MANIFEST_REPO -m legato/releases/$TRAVIS_TAG.xml ;
    else
       repo init -q -u $MANIFEST_REPO -m legato/branches/$TRAVIS_BRANCH.xml ;
    fi
  - repo sync
  - cd legato
  - git remote add local ../../legato-af
  - git fetch local HEAD
  - git reset --hard FETCH_HEAD
  - repo forall -c 'echo -n "$REPO_PATH " && git rev-parse HEAD 2>/dev/null'
  - export JDK_INCLUDE_DIR=/usr/lib/jvm/java-8-openjdk-amd64/include
  - make localhost
  - if [[ "$CC" == "gcc" ]] && ! make all_localhost > /tmp/legato-logs 2>&1 ; then
        echo "Test build failed" && tail -1000 /tmp/legato-logs && exit 1 ;
    fi
